FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/controller

FROM alpine:3.20
WORKDIR /app
COPY --from=build /out/controller /app/controller
EXPOSE 8090
ENTRYPOINT ["/app/controller"]
