global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "controller"
    metrics_path: /metrics
    static_configs:
      - targets: ["controller:8090"]
  - job_name: "demo-workload"
    metrics_path: /metrics
    static_configs:
      - targets: ["demo-workload:9102"]
